# Generated by Django 6.0.1 on 2026-01-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
        ('store', '0003_productvariation_delete_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.productvariation'),
        ),
    ]
